platform :ios, '7.0'
target 'JiafeigouiOS' do

pod 'MJRefresh'
pod 'SDWebImage', '~> 3.7.6'
pod 'Masonry', '~> 1.0.0'
pod 'KVOController'
pod 'SSKeychain'
pod 'Reachability', '~> 3.2'
pod 'MXParallaxHeader', '~> 0.5.0'
pod 'UITableView+FDTemplateLayoutCell_Bell', '~> 1.5.0'
pod 'JZNavigationExtension'
pod 'pop'
pod 'MJExtension'
pod 'Aspects'
pod 'AFNetworking', '~> 3.0'
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'
pod 'weibolive_ios_sdk', '~> 0.0.1'
pod 'FBSDKCoreKit', '~> 4.25.0'
pod 'FBSDKLoginKit', '~> 4.25.0'

end
